### ISSUE TITLE
HUD: Chat Overlay

### ISSUE THREAD

**Issue by alesan99** [alesan99/chicken_society#12]
An overlay that appears at the bottom of the screen at all times.
Should have:

- [x] **Chat:** A text box to type chat messages
- [x] **Emote:** A button that opens a small menu that looks like a nest of eggs. Each egg is a different emote.
- [x] **Customize:** A button that brings up the customization or settings menu.

Needs GUI first: https://github.com/alesan99/chicken_society/issues/4

**Comment by pashiav** [comment]
HI
