### ISSUE TITLE
Bug: Server can crash if for some reason it doesn't properly recieve a player's profile

### ISSUE THREAD

**Issue by alesan99** [alesan99/chicken_society#17]
This happened when opening a bunch of tabs with the game on it until it lagged

**Comment by mcauthon471** [comment]
Unable to replicate bug, stress tested with over 400 tabs(On Server Machine). Never reoccurred. Did notice extreme frame drop with all of the players loaded in the town square. Moved player to another zone and frames returned back to normal, with studder every couple of player inputs. Wondering if this had to do with local machine's specs or if it had to do with packet travel speed and load time being out of sync, where the game loaded before the receiving the packet containing player info.

**Comment by alesan99** [comment]
It happened when connected to like 5 different machines so I believe it was a lost packet. The updateProfile function in server/sync.js seems to be the only function that doesn't check if a player is present in the playerList before attempting an operation so it was probably from that.

**Comment by alesan99** [comment]
Hasn't happened recently and updateProfile has a safety check so it should be good now
