### ISSUE TITLE
Menu: Shop Menu

### ISSUE THREAD

**Issue by alesan99** [alesan99/chicken_society#31]
Should have:

- [x] Neat list of all items with scrolling.
- [x] Previews?
- [x] Tabs for item categories.
- [x] Custom prices and discounts?

**Comment by compelef** [comment]
hello, could you assign this issue to me?
@alesan99 
thank you

**Comment by alesan99** [comment]
Need to add proper scroll bars eventually, but pretty much done.
Deciding against item icons for now
b1f77dd3a91e3598d4e763f50a56e11ff0208765
