### ISSUE TITLE
Login Banner Overlaps Game Canvas :(

### ISSUE THREAD

**Issue by pandrosion** [alesan99/chicken_society#52]
The login banner overlaps part of the game canvas, rendering parts of the backgrounds impossible to see. Is it possible to move that either to the side, or to resize the game canvas so they don't overlap?

![oldtown](https://github.com/alesan99/chicken_society/assets/121267327/7e698780-42cb-4553-a3c1-5aa493d1b175)
<img width="960" alt="Screenshot 2024-01-29 113310" src="https://github.com/alesan99/chicken_society/assets/121267327/1f1bbd48-d250-42d6-a62e-e6b99adb2a95">

**Comment by pashiav** [comment]
it's not the banner overlap, it's an issue with the game canvas resizing
